name: Deploy Frontend App

on:
  push:
    paths:
      - 'frontend/**'
    branches:
      - main
  workflow_dispatch: # Keep this to trigger the deployment manually

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        working-directory: ./frontend
        run: npm install

      - name: Install EAS CLI
        run: npm install -g eas-cli

      - name: Publish to Expo
        working-directory: ./frontend
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
          API_URL: ${{ secrets.API_URL }}
        run: eas update --auto --message "Automated update from GitHub Actions"