name: Deploy Backend Stack

on:
  push:
    paths:
      - 'backend/**'
      - '.github/workflows/github-backend.yml'
#    branches:
#      - main
#      - dev
  workflow_dispatch: # Keep this to trigger the deployment manually

jobs:
  # Stage 1: Install dependencies
  install-depenencies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies for backend
        working-directory: ./backend
        run: npm install

      - name: Build Lambdas
        working-directory: ./backend
        run: npm run build

      - name: Install dependencies for CDK
        working-directory: ./backend/cdk
        run: npm install

      - name: Install AWS CLI
        run: sudo apt-get install awscli -y

      - name: Install AWS CDK
        run: npm install -g aws-cdk@latest

  # Stage 2: CDK diff to check the diff with the prod resources
  diff:
    runs-on: ubuntu-latest
    needs: install-dependencies
    if: github.ref != 'refs/heads/main'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'eu-central-1'

      - name: Set Deployment Environment
        run: echo "DEPLOY_ENV='prod'" >> $GITHUB_ENV

      - name: CDK Diff with prod resources
        if: github.ref != 'refs/heads/main'
        working-directory: ./backend/cdk
        run: |
          echo "Checking CDK diff for production stack"
          cdk diff
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          DEPLOY_ENV: prod

      - name: Deploy Backend Stack
        if: github.ref == 'refs/heads/main'
        working-directory: ./backend/cdk
        run: |
          echo "Deploying to ${{ env.DEPLOY_ENV }}"
          cdk deploy --require-approval never
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          DEPLOY_ENV: ${{ env.DEPLOY_ENV }}

  # Stage 3: Deploy
  deploy:
    runs-on: ubuntu-latest
    needs: install-dependencies
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'eu-central-1'

      - name: Set Deployment Environment
        run: echo "DEPLOY_ENV='prod'" >> $GITHUB_ENV

      - name: Deploy Backend Stack
        working-directory: ./backend/cdk
        run: |
          echo "Deploying to ${{ env.DEPLOY_ENV }}"
          cdk deploy --require-approval never
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          DEPLOY_ENV: ${{ env.DEPLOY_ENV }}